services:
  - type: web
    name: hi-events-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    rootDir: frontend
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
  - type: web
    name: hi-events-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    rootDir: backend
    plan: starter
    envVars:
      - key: APP_ENV
        value: production
