services:
  - type: web
    name: hi-events-backend
    env: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: starter
    envVars:
      - key: APP_ENV
        value: production
